creator_id: orcid:0000-0002-2906-7319
curie_map:
  GTR: http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/GTR/
  HP: http://purl.obolibrary.org/obo/HP_
  mesh: http://identifiers.org/mesh/
  MONDO: http://purl.obolibrary.org/obo/MONDO_
  MEDGEN: http://purl.obolibrary.org/obo/MEDGEN_
  MEDGENCUI: http://purl.obolibrary.org/obo/MEDGENCUI_
  NCIT: http://purl.obolibrary.org/obo/NCIT_
  OMIM: https://omim.org/entry/
  Orphanet: http://www.orpha.net/ORDO/Orphanet_
  orcid: https://orcid.org/
  SCTID: http://identifiers.org/snomedct/
  UMLS: http://purl.obolibrary.org/obo/UMLS_
  oboInOwl: http://www.geneontology.org/formats/oboInOwl#
  owl: http://www.w3.org/2002/07/owl#
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  semapv: https://w3id.org/semapv/
  skos: http://www.w3.org/2004/02/skos/core#
  sssom: https://w3id.org/sssom/
license: http://w3id.org/sssom/license/unspecified
