# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
# About: actions/checkout@v2: Why needed for running code (makefile or not): https://stackoverflow.com/questions/66918575/how-to-use-your-own-makefile-in-github-actions
name: Build and release

on:
  schedule:
    - cron: "0 0 * * 0"  # weekly on Sunday at midnight
  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.4.1
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: make all
    - name: Release
      run: make deploy-release
